#mysql:
#  addr: 119.91.208.25:3306
#  user: douyin
#  passwd: douyin
#  db-name: douyin

mysql:
  addr: 119.91.208.25:3306
  user: douyin
  passwd: douyin
  db-name: douyin

redis:
  addr: 119.91.208.25:6000
  passwd: hanbing

